version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: vulndb
    ports:
      - "3306:3306"

  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
